version: '3.8'
services:
  app:
    build: .
    ports:
      - "${PORT:-8081}:${PORT:-8081}"
    environment:
      - POSTGRES_HOST=db
      - PG_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASS=${POSTGRES_PASS:-123456}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-eventos}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASS:-123456}
      - POSTGRES_DB=${POSTGRES_DATABASE:-eventos}
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
